# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxrandr-dev libx11-dev libgl1-mesa-dev xorg-dev xvfb

    - name: Start Xvfb
      run: |
        Xvfb :99 -screen 0 1024x768x16 &
        export DISPLAY=:99

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .
